{{- if .Values.clickhouse.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ .Release.Name }}-db
    {{- include "openlit.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
  name: {{ .Release.Name }}-db
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{.Release.Name }}-db
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-db
      {{- include "openlit.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-db
        {{- include "openlit.labels" . | nindent 8 }}
        app.kubernetes.io/component: database
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: clickhouse
        image: clickhouse/clickhouse-server
        ports:
        - containerPort: 9000
        - containerPort: 8123
        readinessProbe:
          httpGet:
            path: /ping
            port: 8123
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /ping
            port: 8123
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        env:
        {{- if .Values.clickhouse.auth.secret.name }}
        - name: CLICKHOUSE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.clickhouse.auth.secret.name }}
              key: {{ default "OPENLIT" .Values.clickhouse.auth.secret.passwordKey }}
        - name: CLICKHOUSE_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.clickhouse.secret.name }}
              key: {{ default "default" .Values.clickhouse.auth.secret.usernameKey }}
        {{- else }}
        - name: CLICKHOUSE_PASSWORD
          value: {{ .Values.clickhouse.auth.password | quote }}
        - name: CLICKHOUSE_USER
          value: {{ .Values.clickhouse.auth.user | quote }}
        {{- end }}
        resources:
          {{- toYaml .Values.clickhouse.resources | nindent 12 }}
        volumeMounts:
        - name: {{ .Release.Name }}-db-storage
          mountPath: /var/lib/clickhouse
  volumeClaimTemplates:
  - metadata:
      name: {{ .Release.Name }}-db-storage
    spec:
      accessModes: [ "{{ .Values.clickhouse.persistence.accessMode }}" ]
      resources:
        requests:
          storage: {{ .Values.clickhouse.persistence.size }}
      {{- with .Values.clickhouse.persistence.storageClassName }}
      storageClassName: {{ . }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-db
    {{- include "openlit.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
  name: {{ .Release.Name }}-db
spec:
  ports:
  - port: 9000
    targetPort: 9000
    name: clickhouse
  - port: 8123
    targetPort: 8123
    name: http
  type: {{ .Values.clickhouse.service.type }}
  selector:
    app: {{ .Release.Name }}-db
    {{- include "openlit.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
{{- end }}