apiVersion: v2
name: openlit
description: A Helm chart for OpenLIT
type: application
version: 1.15.0
appVersion: 1.15.0
icon: https://avatars.githubusercontent.com/u/149867240?s=200&v=4
home: https://openlit.io
sources:
  - https://github.com/openlit/openlit
keywords:
  - observability
  - opentelemetry
  - ai
  - ml
  - instrumentation
  - monitoring
  - tracing
maintainers:
  - name: OpenLIT Team
    email: contact@openlit.io
    url: https://openlit.io
