apiVersion: v2
name: openlit
description: A Helm chart for OpenLIT
type: application
version: 0.2.0
appVersion: 0.2.0
icon: https://avatars.githubusercontent.com/u/149867240?s=200&v=4

maintainers:
  - name: patcher9
    email: patcher9@openlit.io
